### ISSUE TITLE
Error to compile x11 dependency

### ISSUE THREAD

**Issue by lemunozm** [ostrosco/device_query#15]
Hi @ostrosco,

Compiling your library in a clean ubuntu18, I got the following error related to your x11 dependency:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"x11\" \"x11 >= 1.4.99.1\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package x11 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `x11.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'x11\' found\nPackage x11 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `x11.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'x11\' found\n" } }', src/libcore/result.rs:1188:5
```

After investigating, I found that it is due to the leak of the x11 development libraries in the system, needed to compile x11.

In ubuntu it can be easily installed with the following command:
```
sudo apt install libx11-dev
```

Maybe it can be useful to add this dependency under a "dependencies" section as part of the readme.

Regards!

**Comment by ostrosco** [comment]
I agree. I'll update the README soon. Thanks for letting me know!

**Comment by ostrosco** [comment]
I've pushed up a new version with an updated README. I'll go ahead and close the issue, but feel free to re-open if you think more information needs to be added. Thanks again for the feedback!
