### ISSUE TITLE
On MacOS, only seems to show mod keys (ctrl, meta, shift)

### ISSUE THREAD

**Issue by SephReed** [ostrosco/device_query#17]
Code taken from here (https://stackoverflow.com/questions/35671985/how-do-i-get-keyboard-input-without-the-user-pressing-the-enter-key)

```rs
use device_query::{DeviceQuery, DeviceState, Keycode};

fn main() {
    let device_state = DeviceState::new();
    loop {
        let keys: Vec<Keycode> = device_state.get_keys();
        for key in keys.iter() {
            println!("Pressed key: {:?}", key);
        }
    }
}
```

None of my character inputs are recognized.  Only stuff like `LControl` or `BackSpace`

**Comment by SephReed** [comment]
I use a custom keyboard layout if that has anything to do with this.

**Comment by ostrosco** [comment]
Thanks for the issue! Unfortunately, I don't have a way to test MacOS issues to try to reproduce them (I've only got a Linux machine). I'm tagging @segeljakt as their libraries are being used for MacOS support in `device_query`. They may have an idea.

**Comment by Chris--B** [comment]
I'm seeing the same thing on Catalina without a custom keyboard layout.
![image](https://user-images.githubusercontent.com/1052157/75321125-1f072500-583e-11ea-9f94-acf89f5039ad.png)

**Comment by segeljakt** [comment]
Strange, I'll take a look at it.

**Comment by segeljakt** [comment]
This is the output I get:
![image](https://user-images.githubusercontent.com/15143039/75384925-19ade700-58df-11ea-8f74-e362af6843db.png)

**Comment by segeljakt** [comment]
I'm on Catalina `10.15.0`, I'm wondering if something changed between that and version `10.15.3` 🤔

**Comment by YXL76** [comment]
According to [dteoh/SlowQuitApps#32](https://github.com/dteoh/SlowQuitApps/issues/32#issuecomment-397792198), this seems to be a permission issue.

**Comment by segeljakt** [comment]
@YXL76 👍 👍 

For anyone troubled, I think you need to give permission to the terminal app you are using (iTerm2, Terminal, Alacritty, etc.) in the system preferences.

**Comment by ostrosco** [comment]
Thanks for figuring this out! I'll update the README soon to add this to the instructions.
