### ISSUE TITLE
Unable to detect Alphanumeric keys in MacOS 11.2.2

### ISSUE THREAD

**Issue by jarnm04** [ostrosco/device_query#34]
My computer is a MacBook Pro running the most recent MacOS (11.2.2). It appears that get_keys() is not picking up when alphanumeric keys, or the spacebar are pressed. Other keys (tab, shit, ctrl, etc.) are detected. From talking with friends, they are experiencing the same issue, and code that does not work on my MacBook runs without issue when performed on Windows.

**Comment by ostrosco** [comment]
Unfortunately this is a permission issue with MacOS that we can't get around (as far as we know, if you have an idea that'd be great). Take a look here for more information: https://github.com/ostrosco/device_query/issues/17

Here's an issue that talked about their solution. https://github.com/dteoh/SlowQuitApps/issues/32

> solved
open MacOS system preference
then go to security/privacy
then click on privacy
scroll down to accessibility
then unlock
then add slowquitapps.app to the list
again, add the app to application data to allow this app access to application data

**Comment by jarnm04** [comment]
Just gave that a shot and got it working. Thanks very much for the quick reply and the reference!
