### ISSUE TITLE
Only meta keys show when calling DeviceState::new().get_keys().

### ISSUE THREAD

**Issue by willdoescode** [ostrosco/device_query#36]
When calling get_keys() from DeviceState, no keys show but shift, backspace, meta, escape, control, and alt.

**Comment by ostrosco** [comment]
What operating system are you using?

**Comment by willdoescode** [comment]
I am on OSX

**Comment by ostrosco** [comment]
Unfortunately this is a permission issue with MacOS that we can't get around (as far as we know, if you have an idea that'd be great). Take a look here for more information: #17

Here's an issue that talked about their solution. dteoh/SlowQuitApps#32

    solved
    open MacOS system preference
    then go to security/privacy
    then click on privacy
    scroll down to accessibility
    then unlock
    then add slowquitapps.app to the list
    again, add the app to application data to allow this app access to application data

**Comment by willdoescode** [comment]
Ok thank you

**Comment by willdoescode** [comment]
Update: I added my terminal to accessibility and now it works.
