### ISSUE TITLE
Add Wayland Support

### ISSUE THREAD

**Issue by helium18** [ostrosco/device_query#43]
My program gives me this error 

`Maximum number of clients reached. Thread 'main' panicked at 'Could not connect to a X display', /home/helium/.cargo/registry/src/github.com-1ecc6299db9ec823/device_query-0.2.8/src/linux/mod.rs:26:17`

And i'm running on Wayland so I suspect that it doesn't support Wayland at the moment. Any plans on adding Wayland support?

**Comment by ostrosco** [comment]
I did look into supporting Wayland a while back. From what I found, Wayland does not provide a mechanism to query the keyboard and mouse state globally for security reasons. I'm sure there's another way to get this information but I wasn't able to track one down. If we can find one, I would love to add Wayland support.

**Comment by helium18** [comment]
Ohh. Since this didn't support Wayland, I decided to make [something](https://github.com/helium18/keylogger/) that works for both Wayland and Xorg sometime back but the problem is, I just made it for my use case (I just want keyboard input). I don't know how one would get the mouse input... Maybe I could try researching about it when I get the time and try contributing :+1:

**Comment by helium18** [comment]
Closing it here...
