### ISSUE TITLE
Support for mouse wheel left & right clicks

### ISSUE THREAD

**Issue by MrTanoshii** [ostrosco/device_query#50]
Is it possible to implement mouse wheel left/right click?

**Comment by ostrosco** [comment]
Maybe? I don't have a mouse that supports mouse wheel left and right clicks to do any testing. We'd just have to see what the OS exposes this as.

**Comment by MrTanoshii** [comment]
My bad, I'm closing this issue; my mouse is a logitech g502 and it actually emulates `Scroll Left` and `Scroll Right` with the mouse wheel side buttons.

But if ever this is implemented, here's a reading list:

https://www.autohotkey.com/docs/KeyList.htm
https://www.autohotkey.com/docs/Hotkeys.htm#HWheel
https://docs.microsoft.com/en-us/windows/win32/controls/wm-hscroll
