### ISSUE TITLE
Misleading docs.rs documentation for methods

### ISSUE THREAD

**Issue by skyslide22** [ostrosco/device_query#55]
some methods noted in https://docs.rs/device_query/1.1.1/device_query/  are not implemented, is this planned in the future or do we have to implement listeners on our own?

e.g: 
```rust
let device_state = DeviceState::new();

 let _guard = device_state.on_mouse_move(|position| {
    println!("Mouse position: {:#?}", position);
 });
```
```no method named `on_mouse_move` found for struct `device_query::DeviceState` in the current scope```

**Comment by ostrosco** [comment]
Hi there!

These methods are implemented but you need to import the DeviceEvents trait. Below is an example code snippet that will work.

```
use device_query::{DeviceState, DeviceEvents};

fn main() {
    let device_state = DeviceState::new();

    let _guard = device_state.on_mouse_move(|position| {
        println!("Mouse position: {:#?}", position);
    });

    loop {}
}
```
