### ISSUE TITLE
about the closure in `on_key_down`(or `on_key_up`)

### ISSUE THREAD

**Issue by lopo12123** [ostrosco/device_query#56]
Hi, thanks for your awesome library.

I'm engaged in front-end development, and recently I'm using `tauri` to make an app that records keystrokes (and want to use `enigo` for autoplay),

But I ran into a problem, in your example (event_based_print_keys.rs),
You use `println!` to print directly to the console, but I'd like to be able to log to a vector for other uses.

However, because `on_key_down`'s parameter `callback ` is of type `Fn` instead of `FnMut`, I cannot modify the outer vector.

Is there any good workaround please, I'm wondering if using `FnMut` here will cause some side effects.
I may not have learned enough about `rust`, I hope you can point out where I am wrong.

Thanks again, this library is very helpful for my development.

- Here's how what I want to do looks like, but it doesn't work
``` rust
pub struct KeyboardEv {
    code: Keycode,
    press: bool,
    timestamp: u128,
}

pub struct KeyboardRecorder {
    ev_queue: Vec<KeyboardEv>,
}

impl KeyboardRecorder {
    pub fn new() -> Self {
        KeyboardRecorder {
            ev_queue: vec![],
        }
    }

    pub fn start_record(&mut self) {
        // instance
        let device_state = DeviceState::new();
        // record start time as zero
        let mut timeline = Instant::now();

        // record press
        let _guard = device_state.on_key_down(|key| {
            println!("down: {:#?}", key);

            let keyCode = key.clone();
            let time_from_zero = timeline.elapsed().as_millis();

            // ▲ i`d like to save custom event record in an outer vector
            self.ev_queue.push(KeyboardEv {
                code: keyCode,
                press: true,
                timestamp: time_from_zero,
            });
        });
        // record release
        // let _guard = device_state.on_key_up(|key| {
        //     println!("up: {:#?}", key);
        // });

        loop {}
    }
}
```

**Comment by ostrosco** [comment]
Hi there! Sorry for taking a while to get back to you.

My thought would be to an Arc<Mutex<T>> here. I've updated your example to show how you may use this pattern. You mentioned you're a bit new to Rust so feel free to ask me any questions!

```rust
use device_query::{Keycode, DeviceState, DeviceEvents};
use std::time::Instant;
use std::sync::{Arc, Mutex};

pub struct KeyboardEv {
    code: Keycode,
    press: bool,
    timestamp: u128,
}

pub struct KeyboardRecorder {
    // Here, we've wrapped your vector in a Arc<Mutex<>> so we can 
    // write to it inside our closure.
    ev_queue: Arc<Mutex<Vec<KeyboardEv>>>,
}

impl KeyboardRecorder {
    pub fn new() -> Self {
        KeyboardRecorder {
            ev_queue: Arc::new(Mutex::new(vec![])),
        }
    }

    pub fn start_record(&mut self) {
        // instance
        let device_state = DeviceState::new();
        // record start time as zero
        let timeline = Instant::now();

        // We make a clone of the Arc<Mutex<>> here so we can move it  
        // into our closure without moving self into the closure.
        let ev_queue = Arc::clone(&self.ev_queue);

        // Note the `move` here on the closure.
        let _guard = device_state.on_key_down(move |key| {
            println!("down: {:#?}", key);

            let key_code = key.clone();
            let time_from_zero = timeline.elapsed().as_millis();

            // We lock the mutex here and write to it.
            let mut ev_queue = ev_queue.lock().unwrap();
            ev_queue.push(KeyboardEv {
                code: key_code,
                press: true,
                timestamp: time_from_zero,
            });
            
        loop {}
    }
}
```

**Comment by lopo12123** [comment]
> 

Thank you so much! Your example perfectly helped me achieve what I wanted.  

By the way, when I sent my demo to my friend to try it out (on `macos monterey ver12.3`) it seems to have found some glitches.  

When recording keystrokes via dq, when encountering these keys (`SHIFT`、`OPTION`、`CONTROL`), it will be recorded as 'left' regardless of whether the press is 'left' or 'right'.  

I can't tell if this is a dq problem or a macos_accessibility_client problem. This has no effect on my use, but I think it may be better to report it to you.

**Comment by ostrosco** [comment]
Thanks! I'll make a separate issue to track it.

**Comment by YMC-GitHub** [comment]
> ```rust
> queue = Arc::clone(&self.ev_queue);
> ```

Thank you!this help.  I'm a bit new to Rust too.
