### ISSUE TITLE
"Maximum number of clients reached" when creating multiple DeviceState

### ISSUE THREAD

**Issue by mdacach** [ostrosco/device_query#57]
![image](https://user-images.githubusercontent.com/43617028/177018166-fea3bd15-3d82-452b-8cc8-9d30b9b4d7df.png)

I have this very simple function that is meant to run multiple times. About two hundred calls into this function, I have the following error:
![image](https://user-images.githubusercontent.com/43617028/177018191-1584217b-d0f9-4e08-acca-573a9f2b5cf2.png)
Pointing me to [this line](https://docs.rs/device_query/0.2.8/src/device_query/linux/mod.rs.html#26)

I suspect it's because I am creating multiple `DeviceState`, and they are not having enough time to close (?)

This is on Manjaro 21 XFCE.

P.S. My original problem is that I need to query the mouse coordinates, but I could not make the `DeviceState` into a static (it does not implement `Sync`), so I was creating one locally every time. I appreciate Rust-specific suggestions for solving this particular problem too (How to make a unique instance of DeviceState where I can query the coords from?)

**Comment by ostrosco** [comment]
Hi there!

My recommendation to work around the situation you have is to just change `check_user_termination` to take a reference to a DeviceState. That way you have to only create one and you can pass it in when you need to do the check.

```rust
fn check_user_termination(device: &DeviceState) {
    let cursor_position = device.get_mouse().coords;
    if cursor_position == (0, 0) {
        panic!("Manual termination through mouse in corner");
    }
}
```

**Comment by mdacach** [comment]
Thank you very much for your answer! 
Unfortunately, that does not work for my specific case because I am using that function as a callback (it must only receive one specific argument (from another crate)). 

In any case, I am not able to reproduce this issue with the X server anymore, and I have no further reason to believe it is indeed happening. So it can stay closed, and thank you very much for your work and quick reply.
[Related issue](https://github.com/nashaofu/display-info/issues/1) on another crate, maybe you could take a look there?
