### ISSUE TITLE
cpu too high on macos

### ISSUE THREAD

**Issue by wuyuedefeng** [ostrosco/device_query#59]
run this demo 
https://github.com/ostrosco/device_query/blob/master/examples/event_based_print_keys.rs

High CPU usage

**Comment by ostrosco** [comment]
Hi there!

There's a few reasons that CPU usage may be high:

* That example has an infinite loop at the end which is gonna spin constantly. That's going to burn a lot of CPU time. Adding a `thread::sleep` in this loop will drop CPU usage significantly.
* The event-based program still has to poll the OS for keyboard and mouse state so there is still quite a bit of looping there checking to see if the state has changed. If you used the non-event driven methods, you can poll at whatever rate you like to drop CPU usage.

Let me know if this helps or if you have any other questions.
