### ISSUE TITLE
Support for wayland onn linux

### ISSUE THREAD

**Issue by dariusgm** [ostrosco/device_query#60]
Hello,

as wayland is now getting the default window manager on several linux distributions, I would very like to see support for it in this lib. 
In case you need support in testing I can try to help.

**Comment by ostrosco** [comment]
Wayland support is by far the most requested feature, but it's currently unknown if it's possible. Last time I looked, Wayland doesn't seem to provide a mechanism for accessing keyboard and mouse state directly for security purposes. There are methods such as polling from /dev/event perhaps, but that would require root privileges.

I'm absolutely open to ways to address this issue. I'll need to look to see if there is a way now to access this information/

**Comment by dariusgm** [comment]
> Wayland support is by far the most requested feature, but it's currently unknown if it's possible. Last time I looked, Wayland doesn't seem to provide a mechanism for accessing keyboard and mouse state directly for security purposes. There are methods such as polling from /dev/event perhaps, but that would require root privileges.
> 
> I'm absolutely open to ways to address this issue. I'll need to look to see if there is a way now to access this information/

I want to build an application that shows the current keys you are pressing and then records this information on video. Basic use case would be for tutorial recordings. root would be ok for me as its only running locally and is build from source.

**Comment by dariusgm** [comment]
I ended up creating something for my usecase by myself. Maybe somebody find it useful as well.

https://github.com/dariusgm/turbo-key
