### ISSUE TITLE
Cannot query keyboard state in linux terminal

### ISSUE THREAD

**Issue by tochiu** [ostrosco/device_query#63]
Hi, I'm trying to use this crate in a TUI I'm developing as a way to detect key-up events but it seems to not detect anything when the terminal is in focus on Linux. Actually, it seems to not work at all unless I have certain other applications in focus--seemingly ones that aren't capturing text input. I'm not sure how to proceed.

Ubuntu 22.04.1 LTS
device_query v1.1.1

**Comment by ostrosco** [comment]
I believe Ubuntu 22.04 uses Wayland by default. This application doesn't work with Wayland. Have you installed the X11 dev libraries?

```
sudo apt install libx11-dev
```

**Comment by tochiu** [comment]
Yes, I have.

**Comment by ostrosco** [comment]
Good news is that I'm able to reproduce the issue so I can start working on a fix. Thanks for letting me know!
