### ISSUE TITLE
question about the `CallbackGuard`

### ISSUE THREAD

**Issue by lopo12123** [ostrosco/device_query#66]
sorry bro, i`m back again.   /(ㄒoㄒ)/~~

Recently i`m writing a node-addon for my electron app to listen some hotkey events (such as ctrl+c for copy).
I use the napi library (https://github.com/napi-rs/napi-rs) to implement the transition from rust to node.

But I encountered a little problem when listening to the button. As written in your example, 

![image](https://user-images.githubusercontent.com/59609929/223342102-e17b974a-b3ac-42ee-b0e5-1ae6b3abeafa.png)

as long as `_guard ` is alive, the listen will always be valid. My idea is to assign the guard returned by the function to a member of the struct so It can be held for a long time, but I don't know what type of this member should be defined, can you give me some help ┭┮﹏┭┮

![image](https://user-images.githubusercontent.com/59609929/223342747-3681057d-4124-4ab3-bc73-39c76ba4f48c.png)
![image](https://user-images.githubusercontent.com/59609929/223342971-c9a77d6a-f1a2-4ff0-bf7c-a0985f775e01.png)

**Comment by ostrosco** [comment]
Hey sorry for taking so long to get back to you. I'm happy to help!

I think all you need to do is add a generic to your Observer struct and specify the traits being implemented there. As an example:

```rust
use device_query::{CallbackGuard, DeviceEvents, DeviceState, Keycode};

pub struct Observer<T, U>
where
    T: Fn(&Keycode) + Sync + Send + 'static,
    U: Fn(&Keycode) + Sync + Send + 'static,
{
    guard_down: Option<CallbackGuard<T>>,
    guard_up: Option<CallbackGuard<U>>,
}

fn main() {
    let device_state = DeviceState::new();
    let guard_down = device_state.on_key_down(|key| {
        println!("Down: {:#?}", key);
    });
    let guard_up = device_state.on_key_up(|key| {
        println!("Up: {:#?}", key);
    });
    let observer = Observer {
        guard_down: Some(guard_down),
        guard_up: Some(guard_up),
    };

    loop {}
}
```

That will let you save the guards in the observer like you're wanting. Lemme know if this helps!
