### ISSUE TITLE
Not functional on Wayland

### ISSUE THREAD

**Issue by redpenguinyt** [ostrosco/device_query#73]
attempting to compile a project with this crate on wayland returns the error 
```Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc' to the PKG_CONFIG_PATH environment variable
Package 'x11', required by 'virtual:world', not found```

**Comment by ostrosco** [comment]
So this library does not support Wayland due to its security policy preventing us from querying global keyboard state. If you install the X11 libraries, you'll be able to get the global keyboard state from programs running under X11 only.
