### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by Neutron3529** [ostrosco/device_query#77]
Currently, another choice for linux user is that, using wayland rather than x11.

But as I tried device_query on my wayland based linux, the demo always returns
```
Current Mouse Coordinates: (94, 1035)
Is A pressed? false
```
It seems that there is no support for wayland now
Is it possible to add wayland support?

**Comment by ostrosco** [comment]
Wayland has a security model that prevents accessing the keyboard and mouse state unless you're the active program so something like `device_query` won't be able to access global keyboard and mouse state this way. Only with root access and a different method of querying the keyboard and mouse state could we do so in Wayland. Sorry.
