### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by kunicmarko20** [ostrosco/device_query#8]
Running the example from https://github.com/ostrosco/device_query/blob/master/examples/print_keys.rs

I just see my process taking more and more memory as I type.

**Comment by ostrosco** [comment]
Windows or Linux? I'll check both, but I'd like to replicate it to see what's going on.

**Comment by kunicmarko20** [comment]
Linux, I just took the example and did `cargo run` in activity monitor I just see my memory going up as I type.

**Comment by ostrosco** [comment]
Thanks for the report! The memory leak has been fixed in version v0.1.2.

**Comment by kunicmarko20** [comment]
Thank you, confirmed it works!
