### ISSUE TITLE
Add wayland support as a feature?

### ISSUE THREAD

**Issue by spencer3035** [ostrosco/device_query#85]
I was wondering if it would be in scope to add wayland support. I could probably do the majority of the programatic work on adding the wayland backend. Not sure the best way to handle the features to determine x11 or wayland. I just wanted to make sure this is a feature that would be accepted before doing too much work on it.

**Comment by ostrosco** [comment]
If you can figure out a way to do it, I'd be more than open to accept a PR. One of Wayland's stated goals is to prevent libraries like this from explicitly doing what it does (i.e. read the keyboard and mouse state while not being the program in focus) so I'm not sure it actually is possible without root access.

**Comment by spencer3035** [comment]
After doing some more in depth research, I think you are correct. You would either need to make a plugin for every wayland compositor (which seems impratical) or need root access. It doesn't seem like there would be a pleasent way to accomplish what this library does in wayland. I'll close the issue.
